[[constraint]]
  name = "github.com/deislabs/porter"
  version = "v0.18.1-beta.1"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.8.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
